In [1]:
import anndata
adata = anndata.read_h5ad('/home/lishiying/data6/SPIDER-paper/ReST3D/results/Lung/Lung5_Rep2.gem.txt.cell_type.monocyte_7PVN/adata.h5ad')

In [3]:
# cell x gene count n*m
adata.to_df()

,LGALS3,SERPINA1,FAS,KITLG,VCAN,CD53,BMP4,NEAT1,CD63,LYZ,...,FABP4,CD69,NegPrb7,TNFRSF10A,NegPrb17,MMP12,FGF12,IFNA1,NRIP3,DPP4
c_2_1_311,7.0,1.0,4.0,1.0,3.0,5.0,1.0,11.0,7.0,26.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_1_383,1.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,5.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_1_513,0.0,0.0,0.0,1.0,3.0,1.0,0.0,6.0,1.0,7.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_1_525,2.0,2.0,0.0,0.0,5.0,0.0,0.0,14.0,0.0,13.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_1_589,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,2.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
c_2_30_3778,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_30_3808,0.0,1.0,0.0,0.0,2.0,2.0,0.0,3.0,1.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_30_3947,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_30_3987,1.0,1.0,0.0,0.0,2.0,1.0,0.0,2.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
c_2_30_4092,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
# conformation n*m'
adata.uns['X']

               0         1         2
MZT2A  -1.034772 -1.038119  1.027191
DUSP5   0.525707  0.871228  0.016519
MALAT1 -1.425137 -1.816856  1.324489
CD74    2.380802 -2.017883  1.560988
COL9A2 -0.225960  1.865090  0.051355
...          ...       ...       ...
CASP8   1.764979  0.452462 -0.061717
NR3C1   1.513145 -0.358040 -1.000590
AZU1   -2.397397 -3.401837  0.922211
BEST1  -1.048677  1.237246 -0.163087
NLRP1  -2.344598 -1.711320  0.088454

[381 rows x 3 columns]

In [7]:
# cell x gene count n*m'
adata.to_df()[adata.uns['X'].index]

,MZT2A,DUSP5,MALAT1,CD74,COL9A2,NEAT1,TYK2,HLA-B,PSAP,SRGN,...,LAMP2,CCL4L2,STAT5A,LIF,NANOG,CASP8,NR3C1,AZU1,BEST1,NLRP1
c_2_1_311,19.0,4.0,7.0,9.0,10.0,11.0,7.0,4.0,4.0,12.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
c_2_1_383,10.0,0.0,3.0,2.0,1.0,6.0,4.0,1.0,0.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_1_513,11.0,1.0,1.0,3.0,0.0,6.0,15.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_1_525,13.0,1.0,5.0,5.0,5.0,14.0,11.0,2.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_1_589,6.0,1.0,1.0,0.0,1.0,1.0,8.0,0.0,1.0,5.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
c_2_30_3778,5.0,2.0,1.0,1.0,1.0,0.0,1.0,3.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_30_3808,9.0,2.0,5.0,1.0,0.0,3.0,13.0,5.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
c_2_30_3947,10.0,4.0,15.0,8.0,1.0,0.0,6.0,4.0,0.0,4.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
c_2_30_3987,3.0,1.0,5.0,3.0,0.0,2.0,3.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
c_2_30_4092,2.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0